'use client';

import { useEffect, useRef, useState, useCallback } from 'react';
import {
  Engine, Scene, ArcRotateCamera, HemisphericLight, DirectionalLight,
  Vector3, Color3, Color4, MeshBuilder, StandardMaterial, Mesh,
  VertexData, LinesMesh,
} from '@babylonjs/core';
import { parseVox, FACE_DIRS, FACE_VERTS, FACE_NORMALS } from '@/lib/vox-parser';

// Outfit voxels were generated by shrinkwrapping to QM body, so they fit
// QM body shape directly. They live under helena_qm/ but can be displayed
// on top of any panel whose body shares QM proportions (qm + helena_qm).
const OUTFIT_SOURCE = '/box5/helena_qm_compare/helena_qm';

const PANELS = [
  { key: 'qm',        label: 'QM (QueenMarika)',  base: '/box5/helena_qm_compare/qm',
    accent: '#fc8', showOutfits: true },
  { key: 'helena',    label: 'Helena (original)', base: '/box5/helena_qm_compare/helena',
    accent: '#fa8', showOutfits: false },
  { key: 'helena_qm', label: 'Helena + QM bones', base: '/box5/helena_qm_compare/helena_qm',
    accent: '#8cf', showOutfits: true },
] as const;

type PanelKey = (typeof PANELS)[number]['key'];

// Shared outfit list (rendered on every panel where showOutfits=true)
const OUTFITS = [
  { key: 'hair',           label: 'Hair',             color: '#fa8' },
  { key: 'bodysuit',       label: 'Bodysuit',         color: '#88f' },
  { key: 'dark_prison_a',  label: 'Dark Prison A',    color: '#a4a' },
  { key: 'dark_prison_b',  label: 'Dark Prison B',    color: '#a4a' },
  { key: 'rs_panties',     label: 'RS Panties',       color: '#fc8' },
  { key: 'rs_shirt_normal', label: 'RS Shirt Normal', color: '#f8f' },
  { key: 'rs_shirt_nude',  label: 'RS Shirt Nude',    color: '#f8f' },
  { key: 'qipao',          label: 'Qipao',            color: '#f48' },
  { key: 'qipao_panty',    label: 'Qipao Panty',      color: '#fc8' },
  { key: 'qipao_shoe',     label: 'Qipao Shoe',       color: '#cca' },
  { key: 'qipao_sock',     label: 'Qipao Sock',       color: '#aaa' },
] as const;

interface Grid {
  voxel_size: number;
  grid_origin: [number, number, number];
  gx: number; gy: number; gz: number;
}

interface SkeletonBone {
  name: string;
  parent: string | null;
  use_deform: boolean;
  head_rest: [number, number, number];
  tail_rest: [number, number, number];
}
interface Skeleton {
  armature: string;
  bone_count: number;
  bones: SkeletonBone[];
}

interface PanelState {
  engine?: Engine;
  scene?: Scene;
  cam?: ArcRotateCamera;
  bodyMesh?: Mesh | null;
  boneLines?: LinesMesh | null;
  outfitMeshes?: Map<string, Mesh>;
  grid?: Grid;
}

// Blender (Z-up) → Babylon (Y-up, 右手系): (bx, bz, -by)
const bToB = (bx: number, by: number, bz: number): [number, number, number] => [bx, bz, -by];

export default function HelenaQmComparePage() {
  const canvasRefs = useRef<Record<PanelKey, HTMLCanvasElement | null>>({
    qm: null, helena: null, helena_qm: null,
  });
  const panelStateRef = useRef<Record<PanelKey, PanelState>>({
    qm: {}, helena: {}, helena_qm: {},
  });
  const syncingRef = useRef(false);

  const [showMesh, setShowMesh] = useState(true);
  const [showSkeleton, setShowSkeleton] = useState(true);
  const [outfitVisible, setOutfitVisible] = useState<Record<string, boolean>>({});
  const [status, setStatusMap] = useState<Record<PanelKey, string>>({
    qm: '...', helena: '...', helena_qm: '...',
  });
  const setStatus = useCallback((k: PanelKey, msg: string) => {
    setStatusMap(s => ({ ...s, [k]: msg }));
  }, []);

  // ---- Camera sync (3 panels stay aligned) ----
  const syncOthers = useCallback((source: ArcRotateCamera, sourceKey: PanelKey) => {
    if (syncingRef.current) return;
    syncingRef.current = true;
    for (const p of PANELS) {
      if (p.key === sourceKey) continue;
      const t = panelStateRef.current[p.key].cam;
      if (!t) continue;
      t.alpha = source.alpha;
      t.beta = source.beta;
      t.radius = source.radius;
      t.target.copyFrom(source.target);
    }
    syncingRef.current = false;
  }, []);

  // ---- Build voxel mesh at world coords ----
  const buildVoxelMesh = useCallback((
    scene: Scene, name: string, voxels: ReturnType<typeof parseVox>['voxels'],
    palette: ReturnType<typeof parseVox>['palette'],
    origin: [number, number, number], voxelSize: number,
    overrideColor?: [number, number, number],
  ): Mesh => {
    const occ = new Set<string>();
    for (const v of voxels) occ.add(`${v.x},${v.y},${v.z}`);
    const positions: number[] = [];
    const normals: number[] = [];
    const colors: number[] = [];
    const indices: number[] = [];

    for (const v of voxels) {
      const col = overrideColor
        ? { r: overrideColor[0], g: overrideColor[1], b: overrideColor[2] }
        : (palette[v.colorIndex - 1] ?? { r: 0.8, g: 0.8, b: 0.8 });
      for (let f = 0; f < 6; f++) {
        const [dx, dy, dz] = FACE_DIRS[f];
        if (occ.has(`${v.x + dx},${v.y + dy},${v.z + dz}`)) continue;
        const bi = positions.length / 3;
        const fv = FACE_VERTS[f], fn = FACE_NORMALS[f];
        const [nx, ny, nz] = bToB(fn[0], fn[1], fn[2]);
        for (let vi = 0; vi < 4; vi++) {
          const [lx, ly, lz] = fv[vi];
          const bx = origin[0] + (v.x + lx) * voxelSize;
          const by = origin[1] + (v.y + ly) * voxelSize;
          const bz = origin[2] + (v.z + lz) * voxelSize;
          const [wx, wy, wz] = bToB(bx, by, bz);
          positions.push(wx, wy, wz);
          normals.push(nx, ny, nz);
          colors.push(col.r, col.g, col.b, 1);
        }
        indices.push(bi, bi + 1, bi + 2, bi, bi + 2, bi + 3);
      }
    }

    const vd = new VertexData();
    vd.positions = positions;
    vd.normals = normals;
    vd.colors = colors;
    vd.indices = indices;
    const mesh = new Mesh(name, scene);
    vd.applyToMesh(mesh);
    const mat = new StandardMaterial(`${name}_mat`, scene);
    mat.disableLighting = true;
    mat.emissiveColor = Color3.White();
    mat.backFaceCulling = false;
    mat.specularColor = Color3.Black();
    mesh.material = mat;
    return mesh;
  }, []);

  // ---- Build bone line system ----
  const buildBoneLines = useCallback((
    scene: Scene, name: string, skel: Skeleton, accent: string,
  ): LinesMesh => {
    const toBabylon = (p: [number, number, number]) => new Vector3(p[0], p[2], -p[1]);
    const lines: Vector3[][] = [];
    const colorArr: Color4[][] = [];
    const accentRGB = Color3.FromHexString(accent);
    const ac = new Color4(accentRGB.r, accentRGB.g, accentRGB.b, 1);
    for (const b of skel.bones) {
      lines.push([toBabylon(b.head_rest), toBabylon(b.tail_rest)]);
      colorArr.push([ac, ac]);
    }
    const lm = MeshBuilder.CreateLineSystem(name, {
      lines, colors: colorArr, updatable: false,
    }, scene);
    lm.isPickable = false;
    return lm;
  }, []);

  // ---- Init scene for one panel ----
  const initPanel = useCallback((canvas: HTMLCanvasElement, key: PanelKey) => {
    const engine = new Engine(canvas, true, { preserveDrawingBuffer: false });
    const scene = new Scene(engine);
    scene.clearColor = new Color4(0.07, 0.07, 0.11, 1);
    scene.useRightHandedSystem = true;

    const cam = new ArcRotateCamera('cam', -Math.PI / 4, Math.PI / 3, 3.0,
      new Vector3(0, 0.95, 0), scene);
    cam.attachControl(canvas, true);
    cam.lowerRadiusLimit = 0.3;
    cam.upperRadiusLimit = 15;
    cam.wheelPrecision = 80;

    const hemi = new HemisphericLight('hemi', new Vector3(0.3, 1, 0.5), scene);
    hemi.intensity = 0.9;
    hemi.groundColor = new Color3(0.2, 0.2, 0.25);
    const dir = new DirectionalLight('dir', new Vector3(-0.5, -1, -0.8), scene);
    dir.intensity = 0.5;

    const ground = MeshBuilder.CreateGround('ground', { width: 4, height: 4, subdivisions: 8 }, scene);
    const gm = new StandardMaterial('gm', scene);
    gm.diffuseColor = new Color3(0.12, 0.12, 0.16);
    gm.specularColor = Color3.Black();
    gm.wireframe = true;
    ground.material = gm;
    ground.position.y = -0.005;

    engine.runRenderLoop(() => scene.render());
    cam.onViewMatrixChangedObservable.add(() => syncOthers(cam, key));

    return { engine, scene, cam };
  }, [syncOthers]);

  // ---- Load voxels + skeleton for one panel ----
  const loadPanel = useCallback(async (
    panel: typeof PANELS[number], scene: Scene,
  ) => {
    setStatus(panel.key, 'loading...');
    try {
      const bust = `?v=${Date.now()}`;
      const [gridResp, voxResp, skelResp] = await Promise.all([
        fetch(`${panel.base}/grid.json${bust}`),
        fetch(`${panel.base}/body.vox${bust}`),
        fetch(`${panel.base}/skeleton.json${bust}`),
      ]);
      if (!gridResp.ok || !voxResp.ok) {
        setStatus(panel.key, 'missing voxel/grid');
        return;
      }
      const grid: Grid = await gridResp.json();
      panelStateRef.current[panel.key].grid = grid;
      const model = parseVox(await voxResp.arrayBuffer());

      const mesh = buildVoxelMesh(
        scene, `body_${panel.key}`, model.voxels, model.palette,
        grid.grid_origin, grid.voxel_size,
      );
      panelStateRef.current[panel.key].bodyMesh = mesh;

      let nBones = 0;
      if (skelResp.ok) {
        const skel: Skeleton = await skelResp.json();
        nBones = skel.bones.length;
        const lm = buildBoneLines(scene, `bones_${panel.key}`, skel, panel.accent);
        panelStateRef.current[panel.key].boneLines = lm;
      }

      // Load outfits (shrinkwrapped to QM body) — render on panels that
      // share QM proportions (qm + helena_qm). Use the OUTFIT_SOURCE grid
      // for placement since outfits were voxelized in that grid.
      const outfitMeshes = new Map<string, Mesh>();
      let outfitVoxTotal = 0;
      if (panel.showOutfits) {
        const ofGridResp = await fetch(`${OUTFIT_SOURCE}/grid.json${bust}`);
        const ofGrid: Grid = ofGridResp.ok ? await ofGridResp.json() : grid;
        for (const o of OUTFITS) {
          try {
            const r = await fetch(`${OUTFIT_SOURCE}/${o.key}.vox${bust}`);
            if (!r.ok) continue;
            const ofModel = parseVox(await r.arrayBuffer());
            if (ofModel.voxels.length === 0) continue;
            const om = buildVoxelMesh(
              scene, `outfit_${panel.key}_${o.key}`,
              ofModel.voxels, ofModel.palette,
              ofGrid.grid_origin, ofGrid.voxel_size,
            );
            om.isVisible = !!outfitVisible[o.key];
            outfitMeshes.set(o.key, om);
            outfitVoxTotal += ofModel.voxels.length;
          } catch (e) {
            console.warn(`outfit ${o.key} failed`, e);
          }
        }
      }
      panelStateRef.current[panel.key].outfitMeshes = outfitMeshes;

      // Voxel index bbox of body (raw counts from .vox)
      let mnX = Infinity, mxX = -Infinity;
      let mnY = Infinity, mxY = -Infinity;
      let mnZ = Infinity, mxZ = -Infinity;
      for (const v of model.voxels) {
        if (v.x < mnX) mnX = v.x; if (v.x > mxX) mxX = v.x;
        if (v.y < mnY) mnY = v.y; if (v.y > mxY) mxY = v.y;
        if (v.z < mnZ) mnZ = v.z; if (v.z > mxZ) mxZ = v.z;
      }
      const wMm = ((mxX - mnX + 1) * grid.voxel_size * 1000).toFixed(0);
      const dMm = ((mxY - mnY + 1) * grid.voxel_size * 1000).toFixed(0);
      const hMm = ((mxZ - mnZ + 1) * grid.voxel_size * 1000).toFixed(0);
      const outfitTag = outfitMeshes.size
        ? ` · ${outfitMeshes.size} outfits (${outfitVoxTotal})`
        : '';
      setStatus(panel.key,
        `body ${model.voxels.length} · ${wMm}×${dMm}×${hMm}mm${nBones ? ` · ${nBones} bones` : ''}${outfitTag}`);
    } catch (e) {
      console.error(`load ${panel.key} failed`, e);
      setStatus(panel.key, `error: ${(e as Error).message ?? e}`);
    }
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [buildVoxelMesh, buildBoneLines, setStatus]);

  // ---- Mount: init all 3 panels ----
  useEffect(() => {
    const cleanups: Array<() => void> = [];
    for (const p of PANELS) {
      const c = canvasRefs.current[p.key];
      if (!c) continue;
      const { engine, scene, cam } = initPanel(c, p.key);
      panelStateRef.current[p.key] = { engine, scene, cam };
      void loadPanel(p, scene);
      const onResize = () => engine.resize();
      window.addEventListener('resize', onResize);
      cleanups.push(() => {
        window.removeEventListener('resize', onResize);
        const st = panelStateRef.current[p.key];
        st.bodyMesh?.dispose();
        st.boneLines?.dispose();
        st.outfitMeshes?.forEach(m => m.dispose());
        engine.dispose();
        panelStateRef.current[p.key] = {};
      });
    }
    return () => { for (const f of cleanups) f(); };
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  // ---- Toggle visibility ----
  useEffect(() => {
    for (const p of PANELS) {
      const m = panelStateRef.current[p.key].bodyMesh;
      if (m) m.isVisible = showMesh;
    }
  }, [showMesh]);
  useEffect(() => {
    for (const p of PANELS) {
      const lm = panelStateRef.current[p.key].boneLines;
      if (lm) lm.isVisible = showSkeleton;
    }
  }, [showSkeleton]);
  useEffect(() => {
    for (const p of PANELS) {
      const ms = panelStateRef.current[p.key].outfitMeshes;
      if (!ms) continue;
      ms.forEach((m, key) => { m.isVisible = !!outfitVisible[key]; });
    }
  }, [outfitVisible]);

  // Outfit list (rendered on panels with showOutfits=true)
  const allOutfits = OUTFITS;

  return (
    <div style={{
      display: 'flex', flexDirection: 'column', height: '100vh',
      background: '#0c0c14', color: '#ddd', fontFamily: 'monospace',
    }}>
      <div style={{
        padding: '8px 14px', background: 'rgba(0,0,0,0.4)',
        borderBottom: '1px solid #333', display: 'flex',
        alignItems: 'center', gap: 16, flexWrap: 'wrap',
      }}>
        <span style={{ color: '#8af', fontSize: 13, fontWeight: 'bold' }}>
          QM / Helena / Helena+QMBones — Voxel & Skeleton Compare
        </span>
        <label style={{ display: 'flex', alignItems: 'center', gap: 6, fontSize: 11 }}>
          <input type="checkbox" checked={showMesh}
            onChange={e => setShowMesh(e.target.checked)} />
          Show body voxels
        </label>
        <label style={{ display: 'flex', alignItems: 'center', gap: 6, fontSize: 11 }}>
          <input type="checkbox" checked={showSkeleton}
            onChange={e => setShowSkeleton(e.target.checked)} />
          Show skeleton
        </label>
        <span style={{ fontSize: 10, color: '#888', marginLeft: 'auto' }}>
          drag to rotate · all 3 cameras synced
        </span>
      </div>

      <div style={{ flex: 1, display: 'flex', minHeight: 0 }}>
        {PANELS.map(p => (
          <div key={p.key} style={{
            flex: 1, display: 'flex', flexDirection: 'column',
            borderRight: '1px solid #222', minWidth: 0,
          }}>
            <div style={{
              padding: '6px 10px', background: 'rgba(0,0,0,0.3)',
              borderBottom: '1px solid #222',
              display: 'flex', alignItems: 'center', gap: 8, fontSize: 11,
            }}>
              <span style={{
                display: 'inline-block', width: 10, height: 10,
                background: p.accent, borderRadius: 2,
              }} />
              <span style={{ color: p.accent, fontWeight: 'bold' }}>{p.label}</span>
              <span style={{ color: '#888', marginLeft: 'auto', fontSize: 10 }}>
                {status[p.key]}
              </span>
            </div>
            <div style={{ flex: 1, position: 'relative', minHeight: 0 }}>
              <canvas
                ref={el => { canvasRefs.current[p.key] = el; }}
                style={{ width: '100%', height: '100%', display: 'block', outline: 'none' }}
              />
            </div>
          </div>
        ))}
      </div>

      {allOutfits.length > 0 && (
        <div style={{
          padding: '6px 14px', background: 'rgba(0,0,0,0.35)',
          borderTop: '1px solid #333', display: 'flex',
          alignItems: 'center', gap: 8, flexWrap: 'wrap',
        }}>
          <span style={{ fontSize: 11, color: '#8fa', fontWeight: 'bold' }}>
            Outfits (QM + Helena+QM panels):
          </span>
          {allOutfits.map(o => (
            <label key={o.key} style={{
              display: 'flex', alignItems: 'center', gap: 4,
              fontSize: 11, padding: '2px 6px',
              background: 'rgba(30,30,50,0.6)', borderRadius: 3,
              cursor: 'pointer',
            }}>
              <input type="checkbox" checked={!!outfitVisible[o.key]}
                onChange={e => setOutfitVisible(s => ({ ...s, [o.key]: e.target.checked }))} />
              <span style={{
                display: 'inline-block', width: 8, height: 8,
                background: o.color, borderRadius: 2,
              }} />
              {o.label}
            </label>
          ))}
        </div>
      )}

      <div style={{
        padding: '6px 14px', background: 'rgba(0,0,0,0.3)',
        borderTop: '1px solid #333', fontSize: 10, color: '#888',
      }}>
        Voxels @ resolution=150, surface-only, shrinkwrap to QM body. Files under{' '}
        <code>public/box5/helena_qm_compare/</code>.
      </div>
    </div>
  );
}
