import { Character } from '@/types/poker/PokerGameTypes'

export const characters: Character[] = [
  {
    id: 0,
    name: "武蔵坊 弁慶",
    personality: "まじめ",
    type: "attack",
    hp: "B",
    attack: "B",
    defense: "C",
    speed: "C",
    intelligence: "C",
    image: "images/character/benkei.png",
    backImage: "images/character/benkei-back.png",
  },
  {
    id: 1,
    name: "伊達 政宗",
    personality: "狡猾",
    type: "defense",
    hp: "C",
    attack: "C",
    defense: "A",
    speed: "A",
    intelligence: "B",
    image: "images/character/date_masamune.png",
    backImage: "images/character/date_masamune-back.png",
  },
  {
    id: 2,
    name: "石田 三成",
    personality: "まじめ",
    type: "defense",
    hp: "C",
    attack: "C",
    defense: "C",
    speed: "A",
    intelligence: "C",
    image: "images/character/ishida_mitsunari.png",
    backImage: "images/character/ishida_mitsunari-back.png",
  },
  {
    id: 3,
    name: "宮本 武蔵",
    personality: "熱血",
    type: "attack",
    hp: "B",
    attack: "A",
    defense: "C",
    speed: "B",
    intelligence: "C",
    image: "images/character/miyamoto_musashi.png",
    backImage: "images/character/miyamoto_musashi-back.png",
  },
  {
    id: 4,
    name: "明智 光秀",
    personality: "狡猾",
    type: "defense",
    hp: "C",
    attack: "C",
    defense: "A",
    speed: "C",
    intelligence: "B",
    image: "images/character/nigaoe_akechi_mitsuhide.png",
    backImage: "images/character/nigaoe_akechi_mitsuhide-back.png",
  },
  {
    id: 5,
    name: "太公望",
    personality: "狡猾",
    type: "defense",
    hp: "C",
    attack: "C",
    defense: "B",
    speed: "C",
    intelligence: "A",
    image: "images/character/nigaoe_taikoubou.png",
    backImage: "images/character/nigaoe_taikoubou.png",
  },
  {
    id: 6,
    name: "武王",
    personality: "まじめ",
    type: "attack",
    hp: "C",
    attack: "C",
    defense: "B",
    speed: "C",
    intelligence: "C",
    image: "images/character/nigaoe_buou_syuu.png",
    backImage: "images/character/nigaoe_buou_syuu.png",
  },
  {
    id: 7,
    name: "チンギス ハーン",
    personality: "狡猾",
    type: "defense",
    hp: "A",
    attack: "B",
    defense: "B",
    speed: "B",
    intelligence: "B",
    image: "images/character/nigaoe_chingisuhan.png",
    backImage: "images/character/nigaoe_chingisuhan.png",
  },
  {
    id: 8,
    name: "張飛",
    personality: "まじめ",
    type: "defense",
    hp: "A",
    attack: "A",
    defense: "C",
    speed: "C",
    intelligence: "C",
    image: "images/character/nigaoe_chouhi.png",
    backImage: "images/character/nigaoe_chouhi.png",
  },
  {
    id: 9,
    name: "達磨大師",
    personality: "熱血",
    type: "attack",
    hp: "C",
    attack: "C",
    defense: "C",
    speed: "A",
    intelligence: "C",
    image: "images/character/nigaoe_daruma_taishi.png",
    backImage: "images/character/nigaoe_daruma_taishi.png",
  },
  {
    id: 10,
    name: "服部 半蔵",
    personality: "熱血",
    type: "attack",
    hp: "C",
    attack: "C",
    defense: "C",
    speed: "A",
    intelligence: "C",
    image: "images/character/nigaoe_hattori_hanzou.png",
    backImage: "images/character/nigaoe_hattori_hanzou.png",
  },
  {
    id: 11,
    name: "本多 忠勝",
    personality: "熱血",
    type: "attack",
    hp: "C",
    attack: "C",
    defense: "C",
    speed: "A",
    intelligence: "C",
    image: "images/character/nigaoe_hondatadakatsu.png",
    backImage: "images/character/nigaoe_hondatadakatsu.png",
  },
  {
    id: 21,
    name: "上杉 謙信",
    personality: "熱血",
    type: "attack",
    hp: "B",
    attack: "A",
    defense: "B",
    speed: "B",
    intelligence: "B",
    image: "images/character/uesugi_kenshin.png",
    backImage: "images/character/uesugi_kenshin.png",
  },
  {
    id: 22,
    name: "武田 信玄",
    personality: "狡猾",
    type: "defense",
    hp: "B",
    attack: "B",
    defense: "A",
    speed: "B",
    intelligence: "B",
    image: "images/character/takeda_shingen.png",
    backImage: "images/character/takeda_shingen.png",
  },
];

export const getCharacterById = (id: number): Character | undefined => {
  return characters.find(char => char.id === id)
}

export const getRandomCharacter = (): Character => {
  const randomIndex = Math.floor(Math.random() * characters.length)
  return characters[randomIndex]
}