import { AnswerPageDataModal, QuestionModal } from "../models/Models";

export const QuestionData: QuestionModal[] = [
	{ TotalPage: 0, QuestionPage:  0, QuestionStep: "STEP 1", QuestionTitle: "仕事について", QuestionText: ""},
	{ TotalPage: 1, QuestionPage:  1, QuestionStep: "STEP 1", QuestionTitle: "仕事について", QuestionText: "非常にたくさんの仕事をしなければならない"},
	{ TotalPage: 2, QuestionPage:  2, QuestionStep: "STEP 1", QuestionTitle: "仕事について", QuestionText: "時間内に仕事が処理しきれない"},
	{ TotalPage: 3, QuestionPage:  3, QuestionStep: "STEP 1", QuestionTitle: "仕事について", QuestionText: "一生懸命働かなければならない"},
	{ TotalPage: 4, QuestionPage:  4, QuestionStep: "STEP 1", QuestionTitle: "仕事について", QuestionText: "かなり注意を集中する必要がある"},
	{ TotalPage: 5, QuestionPage:  5, QuestionStep: "STEP 1", QuestionTitle: "仕事について", QuestionText: "高度の知識や技術が必要なむずかしい仕事だ"},
	{ TotalPage: 6, QuestionPage:  6, QuestionStep: "STEP 1", QuestionTitle: "仕事について", QuestionText: "勤務時間中はいつも仕事のことを考えていなければならない"},
	{ TotalPage: 7, QuestionPage:  7, QuestionStep: "STEP 1", QuestionTitle: "仕事について", QuestionText: "からだを大変よく使う仕事だ"},
	{ TotalPage: 8, QuestionPage:  8, QuestionStep: "STEP 1", QuestionTitle: "仕事について", QuestionText: "自分のぺースで仕事ができる"},
	{ TotalPage: 9, QuestionPage:  9, QuestionStep: "STEP 1", QuestionTitle: "仕事について", QuestionText: "自分で仕事の順番・やり方を決めることができる"},
	{ TotalPage:10, QuestionPage: 10, QuestionStep: "STEP 1", QuestionTitle: "仕事について", QuestionText: "職場の仕事の方針に自分の意見を反映できる"},
	{ TotalPage:11, QuestionPage: 11, QuestionStep: "STEP 1", QuestionTitle: "仕事について", QuestionText: "自分の技能や知識を仕事で使うことが少ない"},
	{ TotalPage:12, QuestionPage: 12, QuestionStep: "STEP 1", QuestionTitle: "仕事について", QuestionText: "私の部署内で意見のくい違いがある"},
	{ TotalPage:13, QuestionPage: 13, QuestionStep: "STEP 1", QuestionTitle: "仕事について", QuestionText: "私の部署と他の部署とはうまが合わない"},
	{ TotalPage:14, QuestionPage: 14, QuestionStep: "STEP 1", QuestionTitle: "仕事について", QuestionText: "私の職場の雰囲気は友好的である"},
	{ TotalPage:15, QuestionPage: 15, QuestionStep: "STEP 1", QuestionTitle: "仕事について", QuestionText: "私の職場の作業環境（騒音、照明、温度、換気など）はよくない"},
	{ TotalPage:16, QuestionPage: 16, QuestionStep: "STEP 1", QuestionTitle: "仕事について", QuestionText: "仕事の内容は自分にあっている"},
	{ TotalPage:17, QuestionPage: 17, QuestionStep: "STEP 1", QuestionTitle: "仕事について", QuestionText: "働きがいのある仕事だ"},
	{ TotalPage:18, QuestionPage: 0, QuestionStep: "", QuestionTitle: "", QuestionText: ""},
	{ TotalPage:19, QuestionPage: 18, QuestionStep: "STEP 2", QuestionTitle: "最近1か月の状態について", QuestionText: "活気がわいてくる"},
	{ TotalPage:20, QuestionPage: 19, QuestionStep: "STEP 2", QuestionTitle: "最近1か月の状態について", QuestionText: "元気がいっぱいだ"},
	{ TotalPage:21, QuestionPage: 20, QuestionStep: "STEP 2", QuestionTitle: "最近1か月の状態について", QuestionText: "生き生きする"},
	{ TotalPage:22, QuestionPage: 21, QuestionStep: "STEP 2", QuestionTitle: "最近1か月の状態について", QuestionText: "怒りを感じる"},
	{ TotalPage:23, QuestionPage: 22, QuestionStep: "STEP 2", QuestionTitle: "最近1か月の状態について", QuestionText: "内心腹立たしい"},
	{ TotalPage:24, QuestionPage: 23, QuestionStep: "STEP 2", QuestionTitle: "最近1か月の状態について", QuestionText: "イライラしている"},
	{ TotalPage:25, QuestionPage: 24, QuestionStep: "STEP 2", QuestionTitle: "最近1か月の状態について", QuestionText: "ひどく疲れた"},
	{ TotalPage:26, QuestionPage: 25, QuestionStep: "STEP 2", QuestionTitle: "最近1か月の状態について", QuestionText: "へとへとだ"},
	{ TotalPage:27, QuestionPage: 26, QuestionStep: "STEP 2", QuestionTitle: "最近1か月の状態について", QuestionText: "だるい"},
	{ TotalPage:28, QuestionPage: 27, QuestionStep: "STEP 2", QuestionTitle: "最近1か月の状態について", QuestionText: "気がはりつめている"},
	{ TotalPage:29, QuestionPage: 28, QuestionStep: "STEP 2", QuestionTitle: "最近1か月の状態について", QuestionText: "不安だ"},
	{ TotalPage:30, QuestionPage: 29, QuestionStep: "STEP 2", QuestionTitle: "最近1か月の状態について", QuestionText: "落着かない"},
	{ TotalPage:31, QuestionPage: 30, QuestionStep: "STEP 2", QuestionTitle: "最近1か月の状態について", QuestionText: "ゆううつだ"},
	{ TotalPage:32, QuestionPage: 31, QuestionStep: "STEP 2", QuestionTitle: "最近1か月の状態について", QuestionText: "何をするのも面倒だ"},
	{ TotalPage:33, QuestionPage: 32, QuestionStep: "STEP 2", QuestionTitle: "最近1か月の状態について", QuestionText: "物事に集中できない"},
	{ TotalPage:34, QuestionPage: 33, QuestionStep: "STEP 2", QuestionTitle: "最近1か月の状態について", QuestionText: "気分が晴れない"},
	{ TotalPage:35, QuestionPage: 34, QuestionStep: "STEP 2", QuestionTitle: "最近1か月の状態について", QuestionText: "仕事が手につかない"},
	{ TotalPage:36, QuestionPage: 35, QuestionStep: "STEP 2", QuestionTitle: "最近1か月の状態について", QuestionText: "悲しいと感じる"},
	{ TotalPage:37, QuestionPage: 36, QuestionStep: "STEP 2", QuestionTitle: "最近1か月の状態について", QuestionText: "めまいがする"},
	{ TotalPage:38, QuestionPage: 37, QuestionStep: "STEP 2", QuestionTitle: "最近1か月の状態について", QuestionText: "体のふしぶしが痛む"},
	{ TotalPage:39, QuestionPage: 38, QuestionStep: "STEP 2", QuestionTitle: "最近1か月の状態について", QuestionText: "頭が重かったり頭痛がする"},
	{ TotalPage:40, QuestionPage: 39, QuestionStep: "STEP 2", QuestionTitle: "最近1か月の状態について", QuestionText: "首筋や肩がこる"},
	{ TotalPage:41, QuestionPage: 40, QuestionStep: "STEP 2", QuestionTitle: "最近1か月の状態について", QuestionText: "腰が痛い"},
	{ TotalPage:42, QuestionPage: 41, QuestionStep: "STEP 2", QuestionTitle: "最近1か月の状態について", QuestionText: "目が疲れる"},
	{ TotalPage:43, QuestionPage: 42, QuestionStep: "STEP 2", QuestionTitle: "最近1か月の状態について", QuestionText: "動悸や息切れがする"},
	{ TotalPage:44, QuestionPage: 43, QuestionStep: "STEP 2", QuestionTitle: "最近1か月の状態について", QuestionText: "胃腸の具合が悪い"},
	{ TotalPage:45, QuestionPage: 44, QuestionStep: "STEP 2", QuestionTitle: "最近1か月の状態について", QuestionText: "食欲がない"},
	{ TotalPage:46, QuestionPage: 45, QuestionStep: "STEP 2", QuestionTitle: "最近1か月の状態について", QuestionText: "便秘や下痢をする"},
	{ TotalPage:47, QuestionPage: 46, QuestionStep: "STEP 2", QuestionTitle: "最近1か月の状態について", QuestionText: "よく眠れない"},
	{ TotalPage:48, QuestionPage: 0, QuestionStep: "", QuestionTitle: "", QuestionText: ""},
	{ TotalPage:49, QuestionPage: 47, QuestionStep: "STEP 3", QuestionTitle: "周りの方々について", QuestionText: "次の人たちとはどのくらい気軽に話ができますか？上司"},
	{ TotalPage:50, QuestionPage: 48, QuestionStep: "STEP 3", QuestionTitle: "周りの方々について", QuestionText: "次の人たちとはどのくらい気軽に話ができますか？職場の同僚"},
	{ TotalPage:51, QuestionPage: 49, QuestionStep: "STEP 3", QuestionTitle: "周りの方々について", QuestionText: "次の人たちとはどのくらい気軽に話ができますか？配偶者、家族、友人等"},
	{ TotalPage:52, QuestionPage: 50, QuestionStep: "STEP 3", QuestionTitle: "周りの方々について", QuestionText: "あなたが困った時、次の人たちはどのくらい頼りになりますか?上司"},
	{ TotalPage:53, QuestionPage: 51, QuestionStep: "STEP 3", QuestionTitle: "周りの方々について", QuestionText: "あなたが困った時、次の人たちはどのくらい頼りになりますか?職場の同僚"},
	{ TotalPage:54, QuestionPage: 52, QuestionStep: "STEP 3", QuestionTitle: "周りの方々について", QuestionText: "あなたが困った時、次の人たちはどのくらい頼りになりますか?配偶者、家族、友人等"},
	{ TotalPage:55, QuestionPage: 53, QuestionStep: "STEP 3", QuestionTitle: "周りの方々について", QuestionText: "あなたの個人的な問題を相談したら、次の人たちはどのくらい聞いてくれますか?上司"},
	{ TotalPage:56, QuestionPage: 54, QuestionStep: "STEP 3", QuestionTitle: "周りの方々について", QuestionText: "あなたの個人的な問題を相談したら、次の人たちはどのくらい聞いてくれますか?職場の同僚"},
	{ TotalPage:57, QuestionPage: 55, QuestionStep: "STEP 3", QuestionTitle: "周りの方々について", QuestionText: "あなたの個人的な問題を相談したら、次の人たちはどのくらい聞いてくれますか?配偶者、家族、友人等"},
	{ TotalPage:58, QuestionPage: 0, QuestionStep: "", QuestionTitle: "", QuestionText: ""},
	{ TotalPage:59, QuestionPage: 56, QuestionStep: "STEP 4", QuestionTitle: "満足度について", QuestionText: "仕事に満足だ"},
	{ TotalPage:60, QuestionPage: 57, QuestionStep: "STEP 4", QuestionTitle: "満足度について", QuestionText: "家庭生活に満足だ"},
	{ TotalPage:61, QuestionPage: 0, QuestionStep: "これで質問は終わりです。", QuestionTitle: "お疲れさまでした。", QuestionText: ""},
]

export const AnswerPageData: AnswerPageDataModal[] = [
	{ ReferencePage:  1, 
		ReferenceStep: "STEP 1", 
		ReferenceTitle: "仕事について", 
		ReferenceTextOne:  "あなたの仕事についてうかがいます。", 
		ReferenceTextTwo:  "4つの中から最もあてはまるものを選んでください。（全17問）", 
		ReferenceTextThree:  "　", 
	},
	{ ReferencePage:  18, 
		ReferenceStep: "STEP 2", 
		ReferenceTitle: "最近1か月の状態について", 
		ReferenceTextOne:  "最近 1 か月間のあなたの状態についてうかがいます。", 
		ReferenceTextTwo:  "最もあてはまるものを選んでください。（全29問）", 
		ReferenceTextThree:  "　", 
	},
	{ ReferencePage:  47, 
		ReferenceStep: "STEP 3", 
		ReferenceTitle: "周りの方々について", 
		ReferenceTextOne:  "あなたの周りの方々についてうかがいます。", 
		ReferenceTextTwo:  "最もあてはまるものを選んでください。（全9問）", 
		ReferenceTextThree:  "　", 
	},
	{ ReferencePage:  56, 
		ReferenceStep: "STEP 4", 
		ReferenceTitle: "満足度について", 
		ReferenceTextOne:  "満足度について（全2問）", 
		ReferenceTextTwo:  "　", 
		ReferenceTextThree:  "　", 
	},
	{ ReferencePage:  58, 
		ReferenceStep: "お疲れさまでした。", 
		ReferenceTitle: "満足度について", 
		ReferenceTextOne:  "　", 
		ReferenceTextTwo:  "　", 
		ReferenceTextThree:  "　", 
	},

]